services:
  - type: web
    name: nessus-analyzer-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: CORS_ORIGINS
        value: https://nessusmerger.vercel.app/ 